apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt-isssuer
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: sujan.poudel@cubit.com.np
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - http01:
                  ingress:
                      class: traefik
