apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.shell }}
      targetPort: shell
      protocol: TCP
      name: shell
    - port: {{ .Values.service.ports.remote1 }}
      targetPort: remote1
      protocol: TCP
      name: remote1   
    - port: {{ .Values.service.ports.remote2 }}
      targetPort: remote2
      protocol: TCP
      name: remote2 
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
