name: Docker build

on:
    push:
        branches:
            - "main"    
jobs:
    build_image:
        permissions:
            packages: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: extractions/setup-just@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{  github.token }}

            - name: Build and push docker image
              run: just build-push-image

    deploy_on_k8:
        runs-on: ubuntu-latest
        needs: build_image
        steps:
            - uses: actions/checkout@v3

            - uses: extractions/setup-just@v2

            - uses: azure/setup-helm@v3

            - uses: azure/setup-kubectl@v3
              name: Setup kubectl client

            - name: create KUBECONFIG
              run: |
                  echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kube-config;
                  chmod 600 kube-config;
                  echo "KUBECONFIG=$(pwd)/kube-config" >> "$GITHUB_ENV"

            - name: Deploy on k8
              run: |
                  kubectl config current-context;
                  just helm-upgrade;
              env:
                  DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON }}